### ISSUE TITLE
Home Page 

### ISSUE THREAD

**Issue by brenbeere** [LiffeyValleyAC/website#39]
TEXT HEADING 
Adjust text sizes:
Interested in running? - Bold text
Enjoy running with other people? - smaller font 
How would you like to move your running to a new level? smaller font 

Insert hyper link to facebook page in text body
highlight facebook page in text

Joining us Today Tab/Link: Link to contact page  

News Column: 
We need to make this standout more or appear as a separate piece
Can you also include as the News headings with relevant links 

1. Tom Brennan Memorial Race Report - Include text from http://liffeyvalleyac.com/race/LVAC-Tom-Brennan-5km-Road-Race/321/ 

2. Tom Brennan Memorial Race Results - link to http://www.precisiontiming.net/result.aspx?v=2289

3. Leinster Senior XC taking place on Sunday 20th January in Dunboyne - link to http://athleticsleinster.org/leinster-fixtures-top

**Comment by mgriffin** [comment]
The Index page is changed now to be a three column layout with the news section in the centre.

The link to the contact us page was added in #55
