### ISSUE TITLE
Nicks Coaching Bio on Training page 

### ISSUE THREAD

**Issue by brenbeere** [LiffeyValleyAC/website#41]
Link to the following text 

Nick Davis is the Liffey Valley AC women’s team coach and has a distinguished record in coaching and athletics administration in Ireland. He has coached athletes to win both National Track, Cross Country Championships and to compete in the World Championships. He has managed Irish Teams at Olympic Games, World Championships and Europa Cup Team Competitions. His coaching philosophy is to help athletes of whatever standard to reach their potential and enjoy this great sport. Nick was President of BLE, the fore runner of AAI and was  instrumental in setting up Athletics Ireland

**Comment by mgriffin** [comment]
Added the text to the main training page for the moment to have it in place
