### ISSUE TITLE
History 

### ISSUE THREAD

**Issue by brenbeere** [LiffeyValleyAC/website#50]
Can you use this image for the HISTORY PAGE 
![history photo](https://cloud.githubusercontent.com/assets/10416680/5700650/10f0dd12-9a39-11e4-87cf-cd9f036a2961.jpg)

**Comment by brenbeere** [comment]
Remove 'fullstop' before  Irish Independent

**Comment by mgriffin** [comment]
Who has the original of this photo? If we can get a bigger version I can use that.

I've removed the reference to the Irish Independent totally. It just wouldn't fit in right with the formatting.

**Comment by brenbeere** [comment]
I took this from facebook site - I think its James Spratts - I can see if he has another version

**Comment by mgriffin** [comment]
Awesome, he sent it on to me, I'll get it updated this afternoon.

**Comment by brenbeere** [comment]
cool Mike

**Comment by mgriffin** [comment]
I've added in the new image, and pushed it live.
