### ISSUE TITLE
Upcoming races 

### ISSUE THREAD

**Issue by brenbeere** [LiffeyValleyAC/website#51]
January 18th 		Leinster Senior XC	
February 8th 		National Masters XC
February 15th 		LVAC Club XC Championship	
March 1st		        National Senior XC	
March 15th 		MSB 5k	
March 29th 		Avondale Cup 4 mile
March 31st 		Club 2 mile	
April 11th 		AAI National 10km
April 18th 		National Road Relays

**Comment by mgriffin** [comment]
I've added these to the calendar.

Next up is to find the locations and start times and I'll add them in when I find them.

**Comment by mgriffin** [comment]
Locations added to most of the races now.
